### ISSUE TITLE
Wrong layout images in readme

### ISSUE THREAD

**Issue by Zi0LEO** [hbmarchive/ferris-sweep#1]
Please fix the readme images, since many of them show some different keys than in the actual layout

**Comment by hbmorrison** [comment]
Looks like I pushed some code into main that shouldn't have been there. I have reverted main to keep things consistent as I haven't looked at this repo for some time and I have little hope of working out what I was thinking with the various QK_LEADs to document them correctly.

**Comment by Zi0LEO** [comment]
Still wrong, but I see you are not maintaining this anymore, I'll fix it myself for what I need. Thanks.

**Comment by hbmorrison** [comment]
No worries. If you detail what is incorrect I will have more of a chance of fixing it.
